---
deployment:
      tasks:
        - export DEPLOYPATH=/home/rrajalaxmi/public_html  # Add /<app_folder> if required
        - /bin/cp -r _site $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
    
